---
version: '2'
services:
  db:
    image: influxdb:1.8
    container_name: influxdb
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    env_file:
      - ./env/db.env
  web:
    # build: ./speedweb
    image: pedrocesarti/internet-speedtest-docker:speedweb
    container_name: speedweb
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    # build: ./speedtest
    image: pedrocesarti/internet-speedtest-docker:speedtest
    container_name: speedtest
    hostname: testing-network1
    links:
      - db:db
    env_file:
      - ./env/testing.env
